version: '3'
services:
  backend:
    image: andyalemonta/backend-build:latest
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: andyalemonta/frontend-build:latest
    container_name: frontend_container
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
